{% set version = "1.035" %}

package:
  name: perl-test-output
  version: {{ version }}

source:
  url: https://github.com/briandfoy/test-output/archive/release-{{ version }}.tar.gz
  sha256: 5acd0f8712892e34af344f82ec97e3ab4897ac652aa8f483a27328cc759ef82c

build:
  number: 0
  script: perl Makefile.PL INSTALLDIRS=site && make && make test && make install
  skip: true  # [win]

requirements:
  build:
    - make
  host:
    - perl
    - perl-capture-tiny
  run:
    - perl
    - perl-capture-tiny

test:
  imports:
    - Test::Output

about:
  home: https://github.com/briandfoy/test-output
  license: Artistic-2.0
  license_file: LICENSE
  summary: Utilities to test STDOUT and STDERR messages
  doc_url: https://metacpan.org/pod/Test::Output

extra:
  recipe-maintainers:
    - '0xaf1f'
